### ISSUE TITLE
How to use this tool

### ISSUE THREAD

**Issue by gietmxh** [theapache64/GPix#1]
i already had api key. But i don't know how to use it

**Comment by theapache64** [comment]
Glad you gained the API-KEY which means you're ready to use the API. :)

Suppose your api key is `abcd123`.
Now give a GET request to http://35.161.57.139:8080/gpix/v1/gpix?keyword=Car (to return images of Car) with header value `Authorization` as `abcd123`. 

More instructions can be found here.

https://github.com/theapache64/GPix/blob/master/README.md

If you still have any doubt, ask me in the comments. Always happy to help.

**Comment by gietmxh** [comment]
how to set header value Authorization with php

**Comment by theapache64** [comment]
You can use cURL to get data from the api. A clear example of adding custom headers and downloading the data can be found here http://stackoverflow.com/a/28347848/4370279

**Comment by gietmxh** [comment]
How to create Gpix without your server. Your server gets content too slowly

**Comment by theapache64** [comment]
I am still working on the project. I'll let you know once the algorithms are working perfectly. Stay tuned.

**Comment by gietmxh** [comment]
Thank for supporting me. I hope this tool has a lot of people use it

**Comment by theapache64** [comment]
You're welcome. :)

**Comment by gietmxh** [comment]
I got new error . I tried to connect to your server but it didn't work

[root@vpsseo ~]# curl http://35.161.57.139:8080/gpix/v1/get_api_key?email=supervphuoc@gmail.com
curl: (7) Failed connect to 35.161.57.139:8080; Connection timed out
[root@vpsseo ~]# ping 35.161.57.139

**Comment by theapache64** [comment]
It's working perfectly here, i dnt knw what's happening there. I'll do a clean check abt the error.
By the way, Where are you from ?

**Comment by gietmxh** [comment]
The first time I used localhost to get your data. It was successfully completed. But when i use on my vps . It didn't work. 

I come from Vietnam. But my vps is located at New jersey

**Comment by theapache64** [comment]
It should work despite the location. There might be some issues with your internet connection. I think so, am not sure. What ever, i'll check all these problems and will tell you the result.

**Comment by gietmxh** [comment]
Thank you so much <3

**Comment by theapache64** [comment]
Welcome again my friend. Actually, GPix has 1 primary server and 36 subordinate servers. The primary server hosted at Amazon (AWS)  under 1 year free tier and other 36 servers are hosted at different locations. The point is everything is hosted for FREE! that might be problem. If you've a good server, we could transfer the program to it or wait for until i purchase a server.

**Comment by theapache64** [comment]
@gietmxh Hey, the API speed has been increased 10 times faster. :) Please check and give me your feedback. :) Thank you.

**Comment by gietmxh** [comment]
@theapache64 Thank you
