### ISSUE TITLE
Invalid API KEY: [KEY]

### ISSUE THREAD

**Issue by BrunoMiguens** [theapache64/GPix#4]
Hi, first of all congratulations for the great job.

I'm trying to create an Access Key to your api but when i try to create i receive this response:
 
```JSON
{
  "error_code": 1,
  "error": true,
  "message": "API key sent to huxijepu@88clean.pro"
}
```

I used a temporary email to show the error but i used an valid email on the first attempts.

So they return an success response with an "valid" key, an error_code and an error with a true value. When i try to use this key the api give me this error:

```JSON
{
  "error_code": 1,
  "error": true,
  "message": "Invalid API KEY: [KEY]"
}
```

**Comment by theapache64** [comment]
Hey Bruno, 
The API has been closed for weeks, but i've reinitiated the system now. Please try again, and let me know if there's any problem exist. Happy GPix-ing. ;)
