### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by NoahDoah** [theapache64/GPix#5]
Thank you so much for this great API. Exactly what I was searching for, for hours now.

I am using this to display random pictures on a website I am doing right now for work. It's about food like cucumber or strawberry and it looks really nice.

It looks best when the background is white/transparent. [Here's a photo](https://i.stack.imgur.com/J7c42.png).

The API usually gives me images with transparent/white backgrounds, but it would be awesome if there were a parameter to search for transparent images, as possible in Google Images.

This would be amazing!

**Comment by theapache64** [comment]
If you want to get images white/transparent background only, simply add it to the keyword.
For example, If you're searching for 'strawberry' images, to get no bg image, the query could be 'strawberry white transparent background'. The point is, you can do it in the query itself. 

Here's an example URL : http://theapache64.xyz:8080/gpix/v1/gpix?Authorization=testApiKey&keyword=Strawberry%20white%20transparent%20background&limit=50

**Comment by NoahDoah** [comment]
Ah, very nice! Thank you so much!

**Comment by theapache64** [comment]
You're welcome. :) :+1:
